import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between">
          <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm sm:flex pt-4 pb-4 mb-8 pl-8 header_bg"
          style={{}}>
            <Link href="/">
              <img src={`/images/pokemonLogo.png`} alt={'logo'} width="150" height="64" />
            </Link>
              <img src={`/images/pokemonGroup.png`} alt={'group'} width="130" height="54" className="mr-8 sm:flex hidden" />
          </div>
          {children}   
        </main>
      </body>
    </html>
  );
}
